name: Docker Build and Publish

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  REPO_NAME: ${{ github.repository }}

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs\/tags\/v}" >> $GITHUB_OUTPUT

      - name: Get the image name
        id: get_name
        run: echo "IMAGE_NAME=${REPO_NAME/docker-}" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build --build-arg VERSION=${{ steps.get_version.outputs.VERSION }} --build-arg BUILD_DATE="$(date +%Y/%m/%dT%H:%M:%S)" --file Dockerfile --tag ${{ steps.get_name.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} .
      
      # Login against a Docker registry
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      
      - name: Push Docker image to registry
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ steps.get_name.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}

      - name: Update latest the Docker image
        if: github.ref == 'refs/heads/main'
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ steps.get_name.outputs.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} ${{ secrets.DOCKER_REGISTRY }}/${{ steps.get_name.outputs.IMAGE_NAME }}:latest

      - name: Push latest Docker image to registry
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ steps.get_name.outputs.IMAGE_NAME }}:latest
